# Generated by Django 4.2.2 on 2023-06-10 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('timeStarted', models.DateTimeField(default=datetime.datetime(2023, 6, 10, 20, 43, 20, 469332))),
                ('timeCompleted', models.DateTimeField(default=datetime.datetime(2023, 6, 10, 20, 43, 20, 469383))),
                ('timeAlloted', models.DurationField(default=datetime.timedelta(0))),
                ('overhead', models.DurationField(default=datetime.timedelta(0))),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='tasks.category')),
            ],
            options={
                'ordering': ['-timeStarted'],
            },
        ),
    ]
