# Generated by Django 4.2.2 on 2023-06-10 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='overhead',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeCompleted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 22, 29, 18, 393961, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 22, 29, 18, 393530, tzinfo=datetime.timezone.utc)),
        ),
    ]
