# Generated by Django 4.2.2 on 2023-06-10 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_overhead_alter_task_timecompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alloted',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeCompleted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 22, 47, 32, 151680, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 22, 47, 32, 151377, tzinfo=datetime.timezone.utc)),
        ),
    ]
